Repository Eyhenij/rt-tools, pull requests merged in 2024-08, with the labels that each got.

#35 30 31 add tollbar and header
  projects/tools/src/lib/ui-kit/aside/components/container/aside-container.component.html
  projects/tools/src/lib/ui-kit/aside/components/container/aside-container.component.scss
  projects/tools/src/lib/ui-kit/aside/components/container/aside-container.component.ts
  projects/tools/src/lib/ui-kit/aside/components/panel/aside-panel.component.scss
  projects/tools/src/lib/ui-kit/aside/stories/aside-component/test-aside.component.html
  projects/tools/src/lib/ui-kit/aside/stories/aside-component/test-aside.component.scss
  projects/tools/src/lib/ui-kit/header/header.component.html
  projects/tools/src/lib/ui-kit/header/header.component.scss
  projects/tools/src/lib/ui-kit/header/header.component.ts
  projects/tools/src/lib/ui-kit/header/index.ts
  projects/tools/src/lib/ui-kit/header/public-api.ts
  projects/tools/src/lib/ui-kit/header/stories/component/header.component.html
  projects/tools/src/lib/ui-kit/header/stories/component/header.component.scss
  projects/tools/src/lib/ui-kit/header/stories/component/header.component.ts
  projects/tools/src/lib/ui-kit/header/stories/header.stories.ts
  projects/tools/src/lib/ui-kit/toolbar/index.ts
  projects/tools/src/lib/ui-kit/toolbar/public-api.ts
  projects/tools/src/lib/ui-kit/toolbar/toolbar.component.html
  projects/tools/src/lib/ui-kit/toolbar/toolbar.component.scss
  projects/tools/src/lib/ui-kit/toolbar/toolbar.component.ts
  projects/tools/src/public-api.ts
  projects/tools/src/styles/_base.scss
Labels: feature

#36 update version
  projects/tools/package.json
Labels: enhancement

#37 common table
  package-lock.json
  package.json
  projects/tools/.storybook/storybook.scss
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/aside/components/container/aside-container.component.scss
  projects/tools/src/lib/ui-kit/aside/components/panel/aside-panel.component.scss
  projects/tools/src/lib/ui-kit/modal/modal.component.scss
  projects/tools/src/lib/ui-kit/scrollable/scrollable-container.component.scss
  projects/tools/src/lib/ui-kit/side-menu/menu-sub-item/rtui-side-menu-sub-item.component.html
  projects/tools/src/lib/ui-kit/side-menu/menu-sub-item/rtui-side-menu-sub-item.component.ts
  projects/tools/src/lib/ui-kit/side-menu/menu/rtui-side-menu.component.html
  projects/tools/src/lib/ui-kit/side-menu/menu/rtui-side-menu.component.ts
  projects/tools/src/lib/ui-kit/side-menu/stories/component/side-menu-wrapper.component.html
  projects/tools/src/lib/ui-kit/side-menu/stories/component/side-menu-wrapper.component.ts
  projects/tools/src/lib/ui-kit/side-menu/stories/side-menu.stories.ts
  projects/tools/src/lib/ui-kit/table/components/clear-search-button/rtui-clear-button.component.html
  projects/tools/src/lib/ui-kit/table/components/clear-search-button/rtui-clear-button.component.scss
  projects/tools/src/lib/ui-kit/table/components/clear-search-button/rtui-clear-button.component.ts
  projects/tools/src/lib/ui-kit/table/components/pagination-view/pagination.component.html
  projects/tools/src/lib/ui-kit/table/components/pagination-view/pagination.component.scss
  projects/tools/src/lib/ui-kit/table/components/pagination-view/pagination.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.html
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.html
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.html
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.ts
  projects/tools/src/lib/ui-kit/table/index.ts
  projects/tools/src/lib/ui-kit/table/public-api.ts
  projects/tools/src/lib/ui-kit/table/stories/component/test-table-component.html
  projects/tools/src/lib/ui-kit/table/stories/component/test-table-component.scss
  projects/tools/src/lib/ui-kit/table/stories/component/test-table-component.ts
  projects/tools/src/lib/ui-kit/table/stories/constants.ts
  projects/tools/src/lib/ui-kit/table/stories/mocks.ts
  projects/tools/src/lib/ui-kit/table/stories/table.stories.ts
  projects/tools/src/lib/ui-kit/table/stories/types.ts
  projects/tools/src/lib/ui-kit/table/table.component.html
  projects/tools/src/lib/ui-kit/table/table.component.scss
  projects/tools/src/lib/ui-kit/table/table.component.ts
  projects/tools/src/lib/ui-kit/table/util/default-pagination.ts
  projects/tools/src/lib/ui-kit/table/util/list-sort-order.enum.ts
  projects/tools/src/lib/ui-kit/table/util/lists.interface.ts
  projects/tools/src/lib/ui-kit/table/util/table-column.interface.ts
  projects/tools/src/lib/ui-kit/toolbar/toolbar.component.html
  projects/tools/src/lib/ui-kit/toolbar/toolbar.component.scss
  projects/tools/src/lib/ui-kit/toolbar/toolbar.component.ts
  projects/tools/src/lib/util/directives/hide-tooltip.directive.ts
  projects/tools/src/lib/util/directives/index.ts
  projects/tools/src/styles/base/_base.scss
  projects/tools/src/styles/base/_mixin.scss
  projects/tools/src/styles/base/_variables.scss
  projects/tools/src/styles/components/_button.scss
  projects/tools/src/styles/components/_form.scss
  projects/tools/src/styles/components/_table.scss
  projects/tools/src/styles/main.scss
Labels: enhancement

#38 change common table styles
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/table/components/clear-search-button/rtui-clear-button.component.html
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.html
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.html
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.html
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.ts
  projects/tools/src/lib/ui-kit/table/stories/constants.ts
  projects/tools/src/lib/ui-kit/table/stories/table.stories.ts
  projects/tools/src/lib/ui-kit/table/table.component.ts
  projects/tools/src/lib/ui-kit/table/util/table-column.interface.ts
  projects/tools/src/public-api.ts
  projects/tools/src/styles/base/_base.scss
Labels: enhancement

#40 change common table inputs
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.html
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.ts
  projects/tools/src/lib/ui-kit/table/stories/component/test-table-component.html
  projects/tools/src/lib/ui-kit/table/stories/component/test-table-component.ts
  projects/tools/src/lib/ui-kit/table/stories/constants.ts
  projects/tools/src/lib/ui-kit/table/stories/table.stories.ts
  projects/tools/src/lib/ui-kit/table/table.component.scss
  projects/tools/src/lib/ui-kit/table/table.component.ts
  projects/tools/src/lib/ui-kit/table/util/lists.interface.ts
  projects/tools/src/lib/ui-kit/table/util/table-column.interface.ts
Labels: enhancement

#42 change table header styles
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.scss
  projects/tools/src/lib/ui-kit/table/stories/component/test-table-component.ts
  projects/tools/src/styles/base/_base.scss
  projects/tools/src/styles/components/_table.scss
Labels: enhancement

#43 change table styles
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/table/components/index.ts
  projects/tools/src/lib/ui-kit/table/components/pagination-view/pagination.component.html
  projects/tools/src/lib/ui-kit/table/components/pagination-view/pagination.component.scss
  projects/tools/src/lib/ui-kit/table/components/pagination-view/rtui-pagination.component.html
  projects/tools/src/lib/ui-kit/table/components/pagination-view/rtui-pagination.component.scss
  projects/tools/src/lib/ui-kit/table/components/pagination-view/rtui-pagination.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.html
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.html
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.ts
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.html
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.scss
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.ts
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.html
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.scss
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.ts
  projects/tools/src/lib/ui-kit/table/public-api.ts
  projects/tools/src/lib/ui-kit/table/stories/component/test-table-component.html
  projects/tools/src/lib/ui-kit/table/stories/constants.ts
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list-component.html
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list-component.scss
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list-component.ts
  projects/tools/src/lib/ui-kit/table/stories/pagination/test-pagination-component.html
  projects/tools/src/lib/ui-kit/table/stories/pagination/test-pagination-component.scss
  projects/tools/src/lib/ui-kit/table/stories/pagination/test-pagination-component.ts
  projects/tools/src/lib/ui-kit/table/stories/stories/dynamic-list.stories.ts
  projects/tools/src/lib/ui-kit/table/stories/stories/pagination.stories.ts
  projects/tools/src/lib/ui-kit/table/stories/stories/table.stories.ts
  projects/tools/src/lib/ui-kit/table/stories/table/test-table-component.html
  projects/tools/src/lib/ui-kit/table/stories/table/test-table-component.scss
  projects/tools/src/lib/ui-kit/table/stories/table/test-table-component.ts
  projects/tools/src/lib/ui-kit/table/table.component.html
  projects/tools/src/styles/base/_base.scss
  projects/tools/src/styles/components/_table.scss
Labels: enhancement

#44 Feature/add actions for table row
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/table/components/pagination-view/rtui-pagination.component.html
  projects/tools/src/lib/ui-kit/table/components/pagination-view/rtui-pagination.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.html
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.ts
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.html
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.ts
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.html
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.scss
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.ts
  projects/tools/src/lib/ui-kit/table/stories/constants.ts
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list.component.html
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list.component.scss
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list.component.ts
  projects/tools/src/lib/ui-kit/table/stories/pagination/test-pagination-component.scss
  projects/tools/src/lib/ui-kit/table/stories/stories/dynamic-list.stories.ts
  projects/tools/src/lib/ui-kit/table/stories/table/test-table-component.html
  projects/tools/src/lib/ui-kit/table/util/lists.interface.ts
  projects/tools/src/lib/ui-kit/table/util/table-column.interface.ts
  projects/tools/src/styles/base/_base.scss
  projects/tools/src/styles/components/_table.scss
Labels: enhancement

#45 use signal in pagination component
  projects/tools/src/lib/ui-kit/table/components/pagination-view/rtui-pagination.component.html
  projects/tools/src/lib/ui-kit/table/components/pagination-view/rtui-pagination.component.ts
Labels: refactoring

#46 refactor(rt:ui-kit): dynamic-list types
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.ts
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.ts
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.ts
Labels: refactoring

#47 add selection column for table
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.html
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.ts
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.html
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.ts
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.html
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.ts
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list.component.html
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list.component.ts
  projects/tools/src/lib/ui-kit/table/stories/stories/dynamic-list.stories.ts
  projects/tools/src/styles/base/_base.scss
  projects/tools/src/styles/components/_table.scss
Labels: feature

#48 refactor: add providers
  projects/tools/package.json
  projects/tools/src/lib/storage/in-memory-storage.service.ts
  projects/tools/src/lib/storage/providers.ts
  projects/tools/src/lib/storage/public-api.ts
  projects/tools/src/lib/storage/storage.factory.ts
  projects/tools/src/lib/storage/storage.service.ts
  projects/tools/src/lib/ui-kit/aside/aside.service.ts
  projects/tools/src/lib/ui-kit/providers.ts
  projects/tools/src/lib/ui-kit/table/stories/stories/dynamic-list.stories.ts
  projects/tools/src/lib/util/providers.ts
  projects/tools/src/lib/util/public-api.ts
  projects/tools/src/lib/util/services/breakpoints.service.ts
  projects/tools/src/lib/util/services/platform.service.ts
  projects/tools/src/public-api.ts
Labels: refactoring

#50 feat: init snackbar
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/header/stories/component/test-header.component.html
  projects/tools/src/lib/ui-kit/header/stories/component/test-header.component.scss
  projects/tools/src/lib/ui-kit/header/stories/component/test-header.component.ts
  projects/tools/src/lib/ui-kit/header/stories/header.stories.ts
  projects/tools/src/lib/ui-kit/snack-bar/index.ts
  projects/tools/src/lib/ui-kit/snack-bar/public-api.ts
  projects/tools/src/lib/ui-kit/snack-bar/snack-bar-config.interface.ts
  projects/tools/src/lib/ui-kit/snack-bar/snack-bar.component.html
  projects/tools/src/lib/ui-kit/snack-bar/snack-bar.component.scss
  projects/tools/src/lib/ui-kit/snack-bar/snack-bar.compontent.ts
  projects/tools/src/lib/ui-kit/snack-bar/snack-bar.service.ts
  projects/tools/src/lib/ui-kit/snack-bar/stories/component/test-snack-bar.component.html
  projects/tools/src/lib/ui-kit/snack-bar/stories/component/test-snack-bar.component.scss
  projects/tools/src/lib/ui-kit/snack-bar/stories/component/test-snack-bar.component.ts
  projects/tools/src/lib/ui-kit/snack-bar/stories/snack-bar.stories.ts
  projects/tools/src/styles/base/_base.scss
Labels: enhancement

#53 add icon transform for table cell improve snackbar
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/animation/index.ts
  projects/tools/src/lib/ui-kit/animation/progress.animation.ts
  projects/tools/src/lib/ui-kit/animation/public-api.ts
  projects/tools/src/lib/ui-kit/snack-bar/public-api.ts
  projects/tools/src/lib/ui-kit/snack-bar/rt-snack-bar.service.ts
  projects/tools/src/lib/ui-kit/snack-bar/snack-bar-config.interface.ts
  projects/tools/src/lib/ui-kit/snack-bar/snack-bar.component.html
  projects/tools/src/lib/ui-kit/snack-bar/snack-bar.component.scss
  projects/tools/src/lib/ui-kit/snack-bar/snack-bar.compontent.ts
  projects/tools/src/lib/ui-kit/snack-bar/snack-bar.service.ts
  projects/tools/src/lib/ui-kit/snack-bar/stories/component/test-snack-bar.component.html
  projects/tools/src/lib/ui-kit/snack-bar/stories/component/test-snack-bar.component.scss
  projects/tools/src/lib/ui-kit/snack-bar/stories/component/test-snack-bar.component.ts
  projects/tools/src/lib/ui-kit/snack-bar/stories/snack-bar.stories.ts
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.html
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.ts
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.html
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.ts
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.html
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.ts
  projects/tools/src/lib/ui-kit/table/stories/constants.ts
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list.component.html
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list.component.ts
  projects/tools/src/lib/ui-kit/table/stories/mocks.ts
  projects/tools/src/lib/ui-kit/table/stories/stories/dynamic-list.stories.ts
  projects/tools/src/lib/ui-kit/table/stories/types.ts
  projects/tools/src/lib/ui-kit/table/util/table-column.interface.ts
  projects/tools/src/lib/util/directives/icon-outlined.directive.ts
  projects/tools/src/public-api.ts
  projects/tools/src/styles/base/_base.scss
  projects/tools/src/styles/components/_snackbar.scss
  projects/tools/src/styles/main.scss
Labels: enhancement

#54 add style generator
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/aside/components/container/aside-container.component.scss
  projects/tools/src/lib/ui-kit/buttons/icon-round/rtui-round-icon-button.component.scss
  projects/tools/src/lib/ui-kit/side-menu/menu/rtui-side-menu.component.scss
  projects/tools/src/lib/ui-kit/snack-bar/stories/component/test-snack-bar.component.scss
  projects/tools/src/lib/ui-kit/table/components/clear-search-button/rtui-clear-button.component.html
  projects/tools/src/lib/ui-kit/table/components/clear-search-button/rtui-clear-button.component.scss
  projects/tools/src/lib/ui-kit/table/components/pagination-view/rtui-pagination.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.html
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.scss
  projects/tools/src/lib/ui-kit/toolbar/toolbar.component.scss
  projects/tools/src/styles/base/_base.scss
  projects/tools/src/styles/base/_mixin.scss
  projects/tools/src/styles/base/_variables.scss
  projects/tools/src/styles/components/_table.scss
Labels: feature

#55 use style generator
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/aside/components/container/aside-container.component.scss
  projects/tools/src/lib/ui-kit/aside/components/panel/aside-panel.component.scss
  projects/tools/src/lib/ui-kit/buttons/icon-round/rtui-round-icon-button.component.scss
  projects/tools/src/lib/ui-kit/scrollable/scrollable-container.component.scss
  projects/tools/src/lib/ui-kit/side-menu/menu/rtui-side-menu.component.scss
  projects/tools/src/lib/ui-kit/side-menu/stories/component/test-side-menu-wrapper.component.html
  projects/tools/src/lib/ui-kit/side-menu/stories/component/test-side-menu-wrapper.component.scss
  projects/tools/src/lib/ui-kit/side-menu/stories/component/test-side-menu-wrapper.component.ts
  projects/tools/src/lib/ui-kit/side-menu/stories/side-menu.stories.ts
  projects/tools/src/lib/ui-kit/snack-bar/snack-bar.component.scss
  projects/tools/src/lib/ui-kit/snack-bar/snack-bar.compontent.ts
  projects/tools/src/lib/ui-kit/spinner/spinner.component.scss
  projects/tools/src/lib/ui-kit/table/components/clear-search-button/rtui-clear-button.component.scss
  projects/tools/src/lib/ui-kit/table/components/pagination-view/rtui-pagination.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.scss
  projects/tools/src/lib/ui-kit/toolbar/toolbar.component.scss
  projects/tools/src/styles/base/_base.scss
  projects/tools/src/styles/base/_mixin.scss
  projects/tools/src/styles/base/_palette.scss
  projects/tools/src/styles/base/_variables.scss
  projects/tools/src/styles/components/_button.scss
  projects/tools/src/styles/components/_snackbar.scss
  projects/tools/src/styles/components/_table.scss
Labels: enhancement

#56 change ui kit components styles
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/aside/components/container/aside-container.component.html
  projects/tools/src/lib/ui-kit/aside/components/container/aside-container.component.scss
  projects/tools/src/lib/ui-kit/aside/components/panel/aside-panel.component.scss
  projects/tools/src/lib/ui-kit/aside/stories/aside-component/test-aside.component.html
  projects/tools/src/lib/ui-kit/modal/modal.component.html
  projects/tools/src/lib/ui-kit/modal/modal.component.scss
  projects/tools/src/lib/ui-kit/modal/stories/modal.stories.ts
  projects/tools/src/lib/ui-kit/modal/stories/test-modal.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.html
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.scss
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list.component.scss
  projects/tools/src/styles/base/_mixin.scss
  projects/tools/src/styles/components/_button.scss
  projects/tools/src/styles/components/_table.scss
Labels: enhancement

#59 Info badge
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/info-badge/badge-info-enum.ts
  projects/tools/src/lib/ui-kit/info-badge/calculate-text-color-based-on-back.ts
  projects/tools/src/lib/ui-kit/info-badge/icon-side.type.ts
  projects/tools/src/lib/ui-kit/info-badge/index.ts
  projects/tools/src/lib/ui-kit/info-badge/info-badge-types.enum.ts
  projects/tools/src/lib/ui-kit/info-badge/info-badge.component.html
  projects/tools/src/lib/ui-kit/info-badge/info-badge.component.scss
  projects/tools/src/lib/ui-kit/info-badge/info-badge.component.ts
  projects/tools/src/lib/ui-kit/info-badge/public-api.ts
  projects/tools/src/lib/ui-kit/info-badge/stories/component/test-info-badge/test-info-badge.component.html
  projects/tools/src/lib/ui-kit/info-badge/stories/component/test-info-badge/test-info-badge.component.scss
  projects/tools/src/lib/ui-kit/info-badge/stories/component/test-info-badge/test-info-badge.component.ts
  projects/tools/src/lib/ui-kit/info-badge/stories/directives/test-info-badge.directive.ts
  projects/tools/src/lib/ui-kit/info-badge/stories/info-badge.stories.ts
  projects/tools/src/lib/ui-kit/info-badge/stories/utils/enum/info-badge-property.enum.ts
  projects/tools/src/lib/util/enums/position.enum.ts
Labels: feature

#60 Feature/implement toggle component
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/file-uploader/index.ts
  projects/tools/src/lib/ui-kit/file-uploader/public-api.ts
  projects/tools/src/lib/ui-kit/file-uploader/rtui-file-upload.component.html
  projects/tools/src/lib/ui-kit/file-uploader/rtui-file-upload.component.scss
  projects/tools/src/lib/ui-kit/file-uploader/rtui-file-upload.component.ts
  projects/tools/src/lib/ui-kit/file-uploader/stories/component/test-file-upload.component.html
  projects/tools/src/lib/ui-kit/file-uploader/stories/component/test-file-upload.component.scss
  projects/tools/src/lib/ui-kit/file-uploader/stories/component/test-file-upload.component.ts
  projects/tools/src/lib/ui-kit/file-uploader/stories/upload.stories.ts
  projects/tools/src/lib/ui-kit/side-menu/menu-sub-item/rtui-side-menu-sub-item.component.html
  projects/tools/src/lib/ui-kit/side-menu/menu-sub-item/rtui-side-menu-sub-item.component.ts
  projects/tools/src/lib/ui-kit/side-menu/menu/rtui-side-menu.component.html
  projects/tools/src/lib/ui-kit/side-menu/menu/rtui-side-menu.component.ts
  projects/tools/src/lib/ui-kit/side-menu/stories/component/test-side-menu-wrapper.component.html
  projects/tools/src/lib/ui-kit/side-menu/stories/component/test-side-menu-wrapper.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.html
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.scss
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.ts
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.html
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.ts
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.html
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.ts
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list.component.html
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list.component.ts
  projects/tools/src/lib/ui-kit/table/stories/stories/dynamic-list.stories.ts
  projects/tools/src/lib/ui-kit/toggle/index.ts
  projects/tools/src/lib/ui-kit/toggle/public-api.ts
  projects/tools/src/lib/ui-kit/toggle/rtui-toggle.component.html
  projects/tools/src/lib/ui-kit/toggle/rtui-toggle.component.scss
  projects/tools/src/lib/ui-kit/toggle/rtui-toggle.component.ts
  projects/tools/src/lib/ui-kit/toggle/stories/component/test-toggle.component.html
  projects/tools/src/lib/ui-kit/toggle/stories/component/test-toggle.component.scss
  projects/tools/src/lib/ui-kit/toggle/stories/component/test-toggle.component.ts
  projects/tools/src/lib/ui-kit/toggle/stories/toggle.stories.ts
  projects/tools/src/lib/ui-kit/toggle/toggle-size.type.enum.ts
  projects/tools/src/lib/ui-kit/toolbar/toolbar.component.scss
  projects/tools/src/lib/util/directives/index.ts
  projects/tools/src/lib/util/directives/navigation.directive.ts
  projects/tools/src/public-api.ts
  projects/tools/src/styles/base/_palette.scss
Labels: feature
