Repository Eyhenij/rt-tools, pull requests merged in 2024-12, with the labels that each got.

#130 update deps
  .github/workflows/main.yml
  .prettierrc.json
  eslint.config.js
  package-lock.json
  package.json
  projects/tools/package.json
Labels: dependencies

#132 remove deprecated styles
  .npmrc
  .nvmrc
  angular.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  projects/tools/.storybook/storybook.scss
  projects/tools/package.json
  projects/tools/src/styles/base/_base.scss
  projects/tools/src/styles/base/_palette.scss
  projects/tools/src/styles/components/_button.scss
  tsconfig.json
Labels: dependencies, refactoring

#133 partial refactor dynamic selector
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/dynamic-selectors/components/dynamic-selector/rtui-dynamic-selector.component.html
  projects/tools/src/lib/ui-kit/dynamic-selectors/components/dynamic-selector/rtui-dynamic-selector.component.ts
  projects/tools/src/lib/ui-kit/dynamic-selectors/components/multi-selector-popup/rtui-multi-selector-popup.component.html
  projects/tools/src/lib/ui-kit/dynamic-selectors/components/multi-selector-popup/rtui-multi-selector-popup.component.ts
  projects/tools/src/lib/ui-kit/dynamic-selectors/strories/component/selector/test-selector.component.html
  projects/tools/src/lib/ui-kit/dynamic-selectors/strories/component/selector/test-selector.component.ts
  projects/tools/src/lib/ui-kit/dynamic-selectors/strories/selector.stories.ts
  projects/tools/src/lib/ui-kit/stories/Configure.mdx
Labels: enhancement

#134 extend filter interface
  projects/tools/package.json
  projects/tools/src/lib/ui-kit/table/util/lists.interface.ts
Labels: enhancement

#135 Refactor/use input types
  .github/workflows/ci.yml
  .github/workflows/main.yml
  projects/tools/src/lib/bem/bem.utils.ts
  projects/tools/src/lib/bem/concat-classes.pipe.ts
  projects/tools/src/lib/storage/json-converter.ts
  projects/tools/src/lib/ui-kit/aside/components/container/aside-container.component.ts
  projects/tools/src/lib/ui-kit/dynamic-selectors/components/actions/rtui-dynamic-selector-list-actions.component.ts
  projects/tools/src/lib/ui-kit/dynamic-selectors/components/dynamic-selector/rtui-dynamic-selector.component.ts
  projects/tools/src/lib/ui-kit/dynamic-selectors/components/dynamic-selectors-directive.ts
  projects/tools/src/lib/ui-kit/dynamic-selectors/components/multi-selector-popup/rtui-multi-selector-popup.component.ts
  projects/tools/src/lib/ui-kit/dynamic-selectors/components/selected-list/rtui-dynamic-selector-selected-list.component.ts
  projects/tools/src/lib/ui-kit/header/header.component.ts
  projects/tools/src/lib/ui-kit/image-uploader/image-uploader/rtui-image-upload.component.ts
  projects/tools/src/lib/ui-kit/side-menu/menu-sub-item/rtui-side-menu-sub-item.component.ts
  projects/tools/src/lib/ui-kit/side-menu/menu/rtui-side-menu.component.ts
  projects/tools/src/lib/ui-kit/spinner/spinner.component.ts
  projects/tools/src/lib/ui-kit/table/components/clear-search-button/rtui-clear-button.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-base-cell/table-base-cell.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-container/table-container.component.ts
  projects/tools/src/lib/ui-kit/table/components/table-header-cell/table-header-cell.component.ts
  projects/tools/src/lib/ui-kit/table/components/table/rtui-table.component.ts
  projects/tools/src/lib/ui-kit/table/dynamic-list.component.ts
  projects/tools/src/lib/ui-kit/table/util/common-selectors.directive.ts
  projects/tools/src/lib/ui-kit/table/util/dynamic-list-selectors.directive.ts
  projects/tools/src/lib/ui-kit/toggle/rtui-toggle.component.ts
  projects/tools/src/lib/ui-kit/toolbar/toolbar.component.ts
  projects/tools/src/lib/util/directives/icon-outlined.directive.ts
  projects/tools/src/lib/util/directives/index.ts
  projects/tools/src/lib/util/directives/scroll.directive.ts
  projects/tools/src/lib/util/functions/sorters.ts
  projects/tools/src/lib/util/helpers/type-cast.helper.ts
Labels: refactoring

#137 ci: update ci.yml
  .github/workflows/publish.yml
Labels: enhancement

#138 ci: remove redundant cd command from publish.yml
  .github/workflows/publish.yml
Labels: enhancement

#139 ci: remove redundant cd command from publish.yml
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: enhancement

#141 Ci/update actions
  .github/workflows/publish.yml
  package.json
  pnpm-lock.yaml
Labels: enhancement

#144 ci: use correct token
  .github/workflows/publish.yml
Labels: enhancement

#146 Ci/update actions
  .github/workflows/publish.yml
  projects/tools/package.json
Labels: enhancement

#149 Ci/conventional changelog
  .gitattributes
  .github/workflows/publish.yml
  package.json
  pnpm-lock.yaml
  projects/tools/CHANGELOG.md
Labels: enhancement

#150 ci: put correct package version into commit message
  .github/workflows/publish.yml
Labels: enhancement

#153 implement action bar + checkbox
  package.json
  pnpm-lock.yaml
  projects/tools/src/lib/ui-kit/action-bar/action-bar-config.interface.ts
  projects/tools/src/lib/ui-kit/action-bar/components/bar/rtui-action-bar.component.html
  projects/tools/src/lib/ui-kit/action-bar/components/bar/rtui-action-bar.component.scss
  projects/tools/src/lib/ui-kit/action-bar/components/bar/rtui-action-bar.component.ts
  projects/tools/src/lib/ui-kit/action-bar/components/container/rtui-action-bar-container.component.html
  projects/tools/src/lib/ui-kit/action-bar/components/container/rtui-action-bar-container.component.scss
  projects/tools/src/lib/ui-kit/action-bar/components/container/rtui-action-bar-container.component.ts
  projects/tools/src/lib/ui-kit/action-bar/components/index.ts
  projects/tools/src/lib/ui-kit/action-bar/index.ts
  projects/tools/src/lib/ui-kit/action-bar/public-api.ts
  projects/tools/src/lib/ui-kit/action-bar/rt-action-bar.service.ts
  projects/tools/src/lib/ui-kit/checkbox/index.ts
  projects/tools/src/lib/ui-kit/checkbox/public-api.ts
  projects/tools/src/lib/ui-kit/checkbox/rtui-checkbox.component.html
  projects/tools/src/lib/ui-kit/checkbox/rtui-checkbox.component.scss
  projects/tools/src/lib/ui-kit/checkbox/rtui-checkbox.component.ts
  projects/tools/src/lib/ui-kit/checkbox/stories/checkbox.stories.ts
  projects/tools/src/lib/ui-kit/checkbox/stories/component/test-checkbox.component.html
  projects/tools/src/lib/ui-kit/checkbox/stories/component/test-checkbox.component.scss
  projects/tools/src/lib/ui-kit/checkbox/stories/component/test-checkbox.component.ts
  projects/tools/src/lib/ui-kit/popover/index.ts
  projects/tools/src/lib/ui-kit/popover/public-api.ts
  projects/tools/src/lib/ui-kit/popover/rt-popover.directive.ts
  projects/tools/src/lib/ui-kit/popover/rtui-popover-container.component.html
  projects/tools/src/lib/ui-kit/popover/rtui-popover-container.component.scss
  projects/tools/src/lib/ui-kit/popover/rtui-popover-container.component.ts
  projects/tools/src/lib/ui-kit/providers.ts
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list.component.html
  projects/tools/src/lib/ui-kit/table/stories/dynamic-list/test-dynamic-list.component.ts
  projects/tools/src/public-api.ts
  projects/tools/src/styles/components/_action-bar.scss
  projects/tools/src/styles/components/_checkbox.scss
  projects/tools/src/styles/main.scss
Labels: feature
